// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adyugcqcbipgwdvjoepf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkeXVnY3FjYmlwZ3dkdmpvZXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MjU0MzYsImV4cCI6MjA4NjUwMTQzNn0.wqaFnI60Xd5S_Rc74kaKJkJcV3Sr8cUK4BgQY6GHu1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});